---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - image: quay.io/keycloak/keycloak-operator:26.7.3@sha256:e3856fd1aeb404f0e6ae2180b01875c8eeebd3748b0e5d955da77b5d41095ae4
          imagePullPolicy: Always
          