---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - image: quay.io/keycloak/keycloak-operator:26.0.7@sha256:95ae31b9538d19f359e6f44946310aa800d414b685eabcc6b978df459c1efca2
          imagePullPolicy: Always
          