---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - image: quay.io/keycloak/keycloak-operator:26.3.3@sha256:e949939f50db37cca8d719bfb8854b4b694813972211c2fc84a21e6ac473f486
          imagePullPolicy: Always
          