apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: docker.io/bitnami/phpmyadmin:5.2.2-debian-12-r23@sha256:0bbcb4b7d50aae2855201798529953a1504332f3a5aeeaaa4beee802910293fe
        imagePullPolicy: IfNotPresent
        
        